spring:
  kafka:
    bootstrap-servers: ${KAFKA_HOST}:${KAFKA_PORT}  # sử dụng KAFKA_HOST và KAFKA_PORT từ env
    consumer:
      group-id: ${KAFKA_GROUP_ID}
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "org.example.dtos"
server:
  port: 8083
