spring:
  application:
    name: IDENTITY-SERVICE

  data:
    redis:
      host: redis
      port: 6379


eureka:
  client:
    service-url:
      defaultZone : ${EUREKA_DEFAULT_ZONE}  


server:
  port: 9898