spring:
  application:
    name: IDENTITY-SERVICE
  sql:
    init:
      mode: always
      data-locations: classpath:sql/url_access.sql
  data:
    redis:
      host: redis
      port: 6379

#eureka:
#  client:
#    service-url:
#      defaultZone : http://localhost:8761/eureka/


server:
  port: 9898